minimum_pre_commit_version: '3.5.0'

repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.3.1
    hooks:
      - id: stylua-github
        name: stylua (Lua formatter)
        files: \.lua$
        pass_filenames: true

  - repo: local
    hooks:
      - id: biome
        name: biome
        entry: nix develop --command biome format --write --no-errors-on-unmatched
        language: system
        files: \.(cjs|css|gql|graphql|html|js|json|jsonc|jsx|mjs|cts|mts|ts|tsx)$
        pass_filenames: true
