name: quality

on:
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      lua: ${{ steps.changes.outputs.lua }}
      biome: ${{ steps.changes.outputs.biome }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            lua:
              - 'lua/**'
              - 'plugin/**'
              - '*.lua'
              - '.luarc.json'
              - '*.toml'
              - 'vim.yaml'
            biome:
              - '.luarc.json'
              - 'biome.json'
              - '.editorconfig'
              - '.pre-commit-config.yaml'
              - 'flake.nix'
              - 'flake.lock'
              - '.github/workflows/quality.yaml'

  lua-format:
    name: Lua Format Check
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.lua == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command stylua --check .

  lua-lint:
    name: Lua Lint Check
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.lua == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command selene --display-style quiet .

  lua-typecheck:
    name: Lua Type Check
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.lua == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Lua LS Type Check
        uses: mrcjkb/lua-typecheck-action@v0
        with:
          checklevel: Warning
          directories: lua
          configpath: .luarc.json

  biome-format:
    name: Biome Format Check
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.biome == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command biome format biome.json .luarc.json
